require:
  - rubocop-rails

AllCops:
  Exclude:
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
    - 'node_modules/**/*'
    - 'config/**/*'
    - 'bin/**/*'
    - 'db/seeds.rb'
    - 'config.ru'
Metrics/LineLength:
  Max: 100
Style/FrozenStringLiteralComment:
  Enabled: false
Style/HashEachMethods:
  Enabled: false
Style/HashTransformKeys:
  Enabled: false
Style/HashTransformValues:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Rails/NotNullColumn:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb
